# MIT License
# 
# Copyright (c) 2023 vanes430
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Use the official minimal Ubuntu 22.04 image as the base image with multi-platform support
# Use the official Node.js 20 Alpine image with multi-platform support
FROM --platform=$TARGETOS/$TARGETARCH node:20-alpine

LABEL author="vanes430" maintainer="admin@vanes430.my.id"
LABEL org.opencontainers.image.source="https://github.com/vanes430/image"
LABEL org.opencontainers.image.licenses=MIT

# Install required dependencies and create the 'container' user
RUN apk add --no-cache \
    ca-certificates \
    curl \
    ffmpeg \
    git \
    fontconfig \
    libwebp-dev \
    sqlite \
    iproute2 \
    openssl \
    tar \
    tzdata \
    && adduser -D -h /home/container container

# Switch to the 'container' user
USER container

# Set environment variables for the container user and working directory
ENV USER=container HOME=/home/container
WORKDIR /home/container

# Copy the entrypoint script and make it executable
COPY ./entrypoint.sh /entrypoint.sh

# Set the default command to run the entrypoint script
CMD [ "/bin/bash", "/entrypoint.sh" ]
