FROM		--platform=$TARGETOS/$TARGETARCH registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL       author="vanes430" maintainer="admin@vanes430.my.id"
LABEL       org.opencontainers.image.source="https://github.com/vanes430/image"
LABEL       org.opencontainers.image.licenses=MIT

RUN	        microdnf install -y fontconfig glibc-langpack-en iproute openssl shadow-utils sqlite tar \
				&& microdnf update -y \
				&& adduser --home-dir /home/container container \
				&& rpm --install https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm \
				&& microdnf install -y zulu22-jre \
				&& microdnf clean all \
				&& sed -i 's/^LANG=.*/LANG="en_US.utf8"/' /etc/locale.conf

ENV			LANG=en_US.UTF-8
ENV			LANGUAGE=en_US:en
ENV			LC_ALL=en_US.UTF-8

ENV			JAVA_HOME=/usr/lib/jvm/zulu22-ca

USER		container
ENV			USER=container HOME=/home/container
WORKDIR		/home/container

COPY		../entrypoint.sh /entrypoint.sh
CMD			[ "/bin/bash", "/entrypoint.sh" ]